"""fase_02_catalogo

Revision ID: 9d440ddbb041
Revises: ed0d5cb3655a
Create Date: 2026-08-20 01:07:15.485879
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d440ddbb041'
down_revision: str | None = 'ed0d5cb3655a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.Enum('text', 'number', 'boolean', 'list_', name='attribute_data_type'), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attributes')),
    sa.UniqueConstraint('name', name=op.f('uq_attributes_name'))
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('currency_from', sa.String(length=3), nullable=False),
    sa.Column('currency_to', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_rates'))
    )
    op.create_index('ix_exchange_rates_pair_effective_at', 'exchange_rates', ['currency_from', 'currency_to', 'effective_at'], unique=False)
    op.create_table('sku_sequences',
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('last_value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('prefix', name=op.f('pk_sku_sequences'))
    )
    op.create_table('attribute_values',
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_attribute_values_attribute_id_attributes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_values'))
    )
    op.create_index('uq_attribute_values_attribute_value', 'attribute_values', ['attribute_id', 'value'], unique=True)
    op.create_table('file_objects',
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_file_objects_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_objects'))
    )
    op.create_index(op.f('ix_file_objects_storage_key'), 'file_objects', ['storage_key'], unique=False)
    op.create_table('brands',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('logo_file_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logo_file_id'], ['file_objects.id'], name=op.f('fk_brands_logo_file_id_file_objects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('name', name=op.f('uq_brands_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_brands_slug'))
    )
    op.create_table('products',
    sa.Column('sku', sa.String(length=20), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=260), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_rule', sa.Enum('FIXED_PEN', 'FIXED_USD', 'USD_CONVERTED', 'COST_USD_MARGIN', 'MANUAL', name='price_rule'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('stock_minimum', sa.Integer(), nullable=False),
    sa.Column('is_serialized', sa.Boolean(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_price >= 0', name=op.f('ck_products_cost_price_non_negative')),
    sa.CheckConstraint('sale_price >= 0', name=op.f('ck_products_sale_price_non_negative')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('product_attribute_values',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('attribute_value_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_values.id'], name=op.f('fk_product_attribute_values_attribute_value_id_attribute_values'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_attribute_values_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'attribute_value_id', name=op.f('pk_product_attribute_values'))
    )
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_objects.id'], name=op.f('fk_product_images_file_id_file_objects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images'))
    )
    op.create_table('product_offers',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('normal_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('offer_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_product_offers_end_after_start')),
    sa.CheckConstraint('offer_price < normal_price', name=op.f('ck_product_offers_offer_below_normal')),
    sa.CheckConstraint('offer_price > 0', name=op.f('ck_product_offers_offer_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_product_offers_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_offers_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_offers'))
    )
    op.create_table('serialized_units',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('imei', sa.String(length=30), nullable=True),
    sa.Column('imei2', sa.String(length=30), nullable=True),
    sa.Column('mac_address', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'PARTIALLY_PAID', 'DELIVERED_ON_CREDIT', 'SOLD', 'IN_REPAIR', 'RETURNED', 'DAMAGED', name='serial_unit_status'), nullable=False),
    sa.Column('purchase_item_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_serialized_units_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serialized_units')),
    sa.UniqueConstraint('imei', name=op.f('uq_serialized_units_imei'))
    )
    op.create_index(op.f('ix_serialized_units_serial_number'), 'serialized_units', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serialized_units_serial_number'), table_name='serialized_units')
    op.drop_table('serialized_units')
    op.drop_table('product_offers')
    op.drop_table('product_images')
    op.drop_table('product_attribute_values')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_table('brands')
    op.drop_index(op.f('ix_file_objects_storage_key'), table_name='file_objects')
    op.drop_table('file_objects')
    op.drop_index('uq_attribute_values_attribute_value', table_name='attribute_values')
    op.drop_table('attribute_values')
    op.drop_table('sku_sequences')
    op.drop_index('ix_exchange_rates_pair_effective_at', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('attributes')
    sa.Enum(name='attribute_data_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='price_rule').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='serial_unit_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###